SwapShop/Controllers/TradesController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Security.Authentication.ExtendedProtection;
using System.Threading.Tasks;
using SwapShop.Data;
using SwapShop.Models;
using SwapShop.Models.ViewModels.Trades;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.View;

namespace SwapShop.Controllers
{
    [Authorize]
    public class TradesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public TradesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
            //this is a universal method to get the current user logged in 

        public async Task<ActionResult> Details(int id)
        {
            // this is the view for the full trade details 
            // this can viewed by both sender and reciever
            var trade = await _context.Trade
                .Include(t => t.Receiver)
                .Include(t => t.Sender)
                .Include(t => t.BarterTrades)
                .ThenInclude(bt => bt.BarterItem)
                .ThenInclude(bt => bt.AppUser)
                .FirstOrDefaultAsync(tad => tad.TradeId == id);

            //this gets all the barterTrades related to both sender and receiver and current trade
            var senderSelectedItems = trade.BarterTrades.Where(bt => bt.BarterItem.AppUserId == trade.ReceiverId);
            var receiverSelectedItems = trade.BarterTrades.Where(bt => bt.BarterItem.AppUserId == trade.SenderId);

            //this converts those selected barterTrades to the BarterItemSelectList view 
                var sender = senderSelectedItems.Select(list => new BarterItemSelectViewModel 
                {
                    Title = list.BarterItem.Title,
                    Description = list.BarterItem.Description,
                    ImagePath = list.BarterItem.ImagePath,
                    Value = list.BarterItem.Value,
                    BarterItemId = list.BarterItem.BarterItemId,
                    RequestedAmount = list.RequestedAmount
                });

           //this converts those selected barterTrades to the BarterItemSelectList view 
                var receiver = receiverSelectedItems.Select(list => new BarterItemSelectViewModel
                {
                    Title = list.BarterItem.Title,
                    Description = list.BarterItem.Description,
                    ImagePath = list.BarterItem.ImagePath,
                    Value = list.BarterItem.Value,
                    BarterItemId = list.BarterItem.BarterItemId,
                    RequestedAmount = list.RequestedAmount
                });

            //this converts the list of selected items and pass them to the  TradeWithItems view 
            var itemsView = new TradeWithItemsViewModel
            {
                TradeId = id,
                Trade = trade,
                ReceiverSelectedItems = receiver.ToList(),
                SenderSelectedItems = sender.ToList()
            };

            //this takes that now defined TradeWithItems views and passes it to the value view model 
            var valueView = new TradeValueViewModel
            {
               Trade = trade,
               TradeId = id,
               Items = itemsView
            };

            return View(valueView);
        }

        public async Task<ActionResult> Create(string id)
        {
        // this gets both the current user and the user(id) being passed through in the url 
        // this defines which is receiver and sender 
            var sender = await GetCurrentUserAsync();
            var receiver = await _userManager.FindByIdAsync(id);
            
            //this will return a view to initiate a trade
              var viewModel = new TradeRequestFormViewModel
            {
                ReceiverId = receiver.ToString(),
                SenderId = sender.Id,
                DateCreated = DateTime.Now
            };
           
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(TradeRequestFormViewModel modelItem, string id)
        {
            try
            {
                // this gets both the current user and the user(id) being passed through in the url 
                // this defines which is receiver and sender 
                var user = await GetCurrentUserAsync();
                var receiverId = await _userManager.FindByIdAsync(id);

                //This creates the initial trade 
                var trade = new Trade
                {
                    Message = modelItem.Message,
                    ReceiverId = receiverId.Id,
                    SenderId = user.Id,
                    DateCreated = DateTime.Now
                };

                _context.Trade.Add(trade);
                await _context.SaveChangesAsync();

                //passes through the senderId, receieverId, tradeId to the Trade method so the user can select their items 
                return RedirectToAction(nameof(Trade), new { receiverId = trade.ReceiverId, tradeId = trade.TradeId, senderId = user.Id});
            }
            catch
            {
                return View();
            }
        }

        public async Task<ActionResult> Trade(int tradeId, string receiverId, string senderId)
        {
            //find the current user logged in 
            var user = await GetCurrentUserAsync();

            //this allows for either use (sender or receiver) to access the others items. 
            List<BarterItem> barterItems = null;

            //this is getting the trade that we are passing through  
            var trade = await _context.Trade
                        .Include(b => b.BarterTrades)
                        .FirstOrDefaultAsync(o => o.TradeId == tradeId);

            //that empty list of barter items is populated with the users items here 
            if (user.Id.ToString() == senderId)
            {
                barterItems = await _context.BarterItem
                                    .Where(bi => bi.AppUserId == receiverId && bi.IsAvailable == true)
                                    .Include(bi => bi.AppUser)
                                    .ToListAsync();
            }else
            {
                barterItems = await _context.BarterItem
                                    .Where(bi => bi.AppUserId == senderId && bi.IsAvailable == true)
                                    .Include(bi => bi.AppUser)
                                    .ToListAsync();
            }

            //this takes the now populated list of barter items and gets all the data relating to it 
            var checkboxItems = barterItems.Select(cbi => new BarterItemSelectViewModel()
            {
                Title = cbi.Title,
                Description = cbi.Description,
                ImagePath = cbi.ImagePath,
                Value = cbi.Value,
                BarterItemId = cbi.BarterItemId,
                IsSelected = false
            });

            //this will take those items and populate either selectedItems list for the user to choose 
            var viewModel = new TradeWithItemsViewModel
            {
                TradeId = tradeId,
                Trade = trade,
                ReceiverSelectedItems = checkboxItems.ToList(),
                SenderSelectedItems = checkboxItems.ToList()
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Trade(TradeWithItemsViewModel viewModelItem)
        {
            try
            {
                //find current user logged in 
                var user = await GetCurrentUserAsync();

                //find the existing trade the user is working with 
                var tradeRequestExists = await _context.Trade.FirstOrDefaultAsync(o => o.TradeId == viewModelItem.TradeId);
                
                //this says the trade on the viewModel is the current trade we got 
                viewModelItem.Trade = tradeRequestExists;

                //this is renders either checkbox items for whatever user is logged in 
                if (viewModelItem.Trade.SenderId == user.Id)
                {
                    //this grabs all selected items and creates new barterTrades 
                    var senderSelectedItems = viewModelItem.SenderSelectedItems.Where(vmi => vmi.IsSelected == true)
                    .Select(si => new BarterTrade
                    {
                        BarterItemId = si.BarterItemId,
                        TradeId = tradeRequestExists.TradeId,
                        RequestedAmount = si.RequestedAmount
                    });
                        tradeRequestExists.BarterTrades = senderSelectedItems.ToList();
                }
                else
                {
                    //this grabs all selected items and creates new barterTrades 
                    var receiverSelectedItems = viewModelItem.ReceiverSelectedItems.Where(vmi => vmi.IsSelected == true)
                    .Select(si => new BarterTrade
                    {
                        BarterItemId = si.BarterItemId,
                        TradeId = tradeRequestExists.TradeId,
                        RequestedAmount = si.RequestedAmount
                    });
                        tradeRequestExists.BarterTrades = receiverSelectedItems.ToList();

SwapShop/Controllers/UsersController.cs
using SwapShop.Data;
using SwapShop.Models;
using SwapShop.Models.ViewModels.Profile;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace SwapShop.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {

        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        public UsersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {

            _context = context;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var user = await GetCurrentUserAsync();
            var users = await _context.ApplicationUsers
                .Where(bi => bi.Id != user.Id)
                .ToListAsync();

            return View(users);
        }

        // GET: Profile/Details/5
        public async Task<IActionResult> Details(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            var currentUser = await GetCurrentUserAsync();

            var userInfo = await _context.ApplicationUsers
                .Where(app => app.Id == user.Id)
                    .Include(bi => bi.MyBarterItems)
                    .Include(bi => bi.ReceivedTrades)
                        .ThenInclude(t => t.Sender)
                    .Include(bi => bi.SentTrades)
                        .ThenInclude(t => t.Receiver)
                    .ToListAsync();

            var userId = await _context.ApplicationUsers.FirstOrDefaultAsync(app => app.Id == id);

            var completedRequests = user.ReceivedTrades.Concat(user.SentTrades);

            var viewModel = new UserProfileViewModel()
            {
                User = user,
                AppUserId = userId.Id,
                BarterItems = userId.MyBarterItems.ToList(),
                ReceivedTrades = userId.ReceivedTrades.Where(t => t.IsCompleted == false).ToList(),
                SentTrades = userId.SentTrades.Where(t => t.IsCompleted == false).ToList(),
                CompletedTrades = completedRequests.Where(t => t.IsCompleted == true).ToList()
            };

            return View(viewModel);
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public async Task<ActionResult> Edit(int id)
        {
            var user = await GetCurrentUserAsync();
            var viewModel = new ProfileFormViewModel
            {
                AppUserId = user.Id,
                TagName = user.TagName,
                Location = user.Location,
                ImagePath = user.ImagePath
            };

            return View(viewModel);
        }

        // POST: Profiles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind("AppUserId,TagName,Location,ImagePath,ImageFile")]ProfileFormViewModel viewModelItem, int id)
        {
            try
            {
                var profileData = await GetCurrentUserAsync();

                profileData.TagName = viewModelItem.TagName;
                profileData.Location = viewModelItem.Location;


                if (viewModelItem.ImageFile != null && viewModelItem.ImageFile.Length > 0)
                {

                    var fileName = Guid.NewGuid().ToString() + Path.GetFileName(viewModelItem.ImageFile.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", fileName);

                    profileData.ImagePath = fileName;

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await viewModelItem.ImageFile.CopyToAsync(stream);
                    }

                }

                _context.ApplicationUsers.Update(profileData);
                await _context.SaveChangesAsync();

                return RedirectToAction("Details", new { id = viewModelItem.AppUserId });
            }

            catch
            {
                return View();
            }
        }
    }
}

SwapShop/Views/Users/Details.cshtml
@model SwapShop.Models.ViewModels.Profile.UserProfileViewModel
@{
    ViewData["Title"] = "Details";
}

@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager


        <h1 style="color:goldenrod">@Model.User.TagName</h1>
    
<table>
    <br />
        <tt>
            <img src="~/images/@Model.User.ImagePath" , style="width: 20em; height: auto;">
        </tt>
    <br />
        <br />
        <td>
            <a href='@Url.Action("Search","Home")?searchBar=@Model.User.Location'>@Model.User.Location</a>
        </td>
</table>
<div>
    @if (UserManager.GetUserAsync(User).Result.Id == Model.AppUserId)
    {
        <a type="button" class="btn btn-dark" style="background-color:indianred"
           asp-controller="Users" asp-action="Edit" asp-route-id="@Model.AppUserId">
            Edit Profile Information
        </a>
    }
@if (UserManager.GetUserAsync(User).Result.Id != Model.AppUserId && Model.BarterItems.Where(bt => bt.AppUserId == Model.AppUserId) != null)
    {
        <a type="button" class="btn btn-dark" style="background-color:indianred"
           asp-controller="Trades" asp-action="Create" asp-route-id="@Model.AppUserId">
            Make Barter Request
        </a>

    }
</div>

<table class="table">
    @if (UserManager.GetUserAsync(User).Result.Id == Model.AppUserId && Model.SentTrades.Count > 0)
    {

        <th>
            @Html.DisplayNameFor(model => model.SentTrades)
        </th>


        @foreach (var item in Model.SentTrades)
        {
            <tbody>
            <td>
                <a asp-controller="Trades" asp-action="Details" asp-route-id="@item.TradeId">
                    @Html.ActionLink(item.Message, // <-- Link text
                      "Details", // <-- Action Method Name
                      "Trades", // <-- Controller Name
                      new { Id = item.TradeId }, // <-- Route value
                      null // <-- htmlArguments
                      )
                </a>
            </td>
            </tbody>
        }

    }

    @if (UserManager.GetUserAsync(User).Result.Id == Model.AppUserId && Model.CompletedTrades.Count > 0)
    {


        <th>
            @Html.DisplayNameFor(model => model.CompletedTrades)
        </th>


        @foreach (var item in Model.CompletedTrades)
        {


            <tbody>
            <td>
                <a asp-controller="Trades" asp-action="Details" asp-route-id="@item.TradeId">
                    @Html.ActionLink(item.Message, // <-- Link text
                   "Details", // <-- Action Method Name
                   "Trades", // <-- Controller Name
                   new { Id = item.TradeId }, // <-- Route value
                   null // <-- htmlArguments
                   )
                </a>
            </td>
            </tbody>
        }
    }

    @if (UserManager.GetUserAsync(User).Result.Id == Model.AppUserId && Model.ReceivedTrades.Count > 0)
    {
 
            <th>
                @Html.DisplayNameFor(model => model.ReceivedTrades)
            </th>
 

            @foreach (var item in Model.ReceivedTrades)
            {


                <tbody>
                <td>
                    <a asp-controller="Trades" asp-action="Details" asp-route-id="@item.TradeId">
                        @Html.ActionLink(item.Message, // <-- Link text
                       "Details", // <-- Action Method Name
                       "Trades", // <-- Controller Name
                       new { Id = item.TradeId }, // <-- Route value
                       null // <-- htmlArguments
                       )
                    </a>
                </td>
                </tbody>
            }
        }
       
</table>
   


<table class="table">

    @if (Model.BarterItems.Count > 0)
    {
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BarterItems)
            </th>

        </tr>
        @foreach (var item in Model.BarterItems)
        {
            <tbody>

                <tr>
                    @if (item.ImagePath == null)
                    {

                        <th>
                            @Html.DisplayNameFor(model => item.ImagePath)
                        </th>
                        <td>
                            <a asp-controller="BarterItems" asp-action="Details" asp-route-id="@item.BarterItemId">
                                @Html.ActionLink(item.Title, // <-- Link text
                  "Details", // <-- Action Method Name
                  "BarterItems", // <-- Controller Name
                  new { Id = item.BarterItemId }, // <-- Route value
                  null // <-- htmlArguments
                  )
                            </a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                    }
                    else
                    {
                        <td>
                            <a href="@Url.Action("Details", "BarterItems", new { Id = item.BarterItemId })">
                                <img src="~/images/@item.ImagePath" , style="width: 4em; height: auto;">
                            </a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                    }

                    @if (UserManager.GetUserAsync(User).Result.Id == item.AppUserId)
                    {
                        <td>
                            <a asp-controller="BarterItems" asp-action="Edit" asp-route-id="@item.BarterItemId">Edit </a>
                            <a asp-controller="BarterItems" asp-action="Delete" asp-route-id="@item.BarterItemId">Delete</a>
                        </td>
                    }

                @if (item.IsAvailable == false)
                {
                <td>
                    Not Available for Trade
                </td>
            }
                </tr>
                </tbody>
            }

    }
</table>

SwapShop/Views/Users/Edit.cshtml
@model SwapShop.Models.ViewModels.Profile.ProfileFormViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Profile Information</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="@Model.AppUserId" />
            <div class="form-group">
                <label asp-for="TagName" class="control-label"></label>
                <input asp-for="TagName" class="form-control" />
                <span asp-validation-for="TagName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label">Upload an Image</label>
                <input asp-for="ImageFile" type="file" class="form-control" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SwapShop/Views/Users/Index.cshtml
@model IEnumerable<SwapShop.Models.ApplicationUser>

@{
    ViewData["Title"] = "Index";
}

<h1>Community</h1>




        @foreach (var item in Model)

        {
<div class="flex-wrap" style="flex-direction:column; display:inline-flex">
    <div class="card text-white bg-info m-3" style="max-width: 20rem; align-content:center; text-align: center">

        <a href="@Url.Action("Details", "Users",  new { Id = item.Id })">
            <img src="~/images/@item.ImagePath" , style="width: 20em; height: auto;">
        </a>
        <br />
        <a href="@Url.Action("Details", "Users",  new { Id = item.Id })">
            @Html.DisplayFor(modelItem => item.TagName)
        </a>
    </div>
</div>
    }