SwapShop/Controllers/BarterItemsController.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SwapShop.Data;
using SwapShop.Models;
using SwapShop.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.IO;
using SwapShop.Models.ViewModels.BarterItems;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc;

namespace SwapShop.Controllers
{
  
        [Authorize]
        public class BarterItemsController : Controller
        {

            private readonly ApplicationDbContext _context;

            private readonly UserManager<ApplicationUser> _userManager;

            public BarterItemsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
            {

                _context = context;
                _userManager = userManager;
            }
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
        // GET: BarterItems
        public async Task<IActionResult> Index()
        {
            var user = await GetCurrentUserAsync();
            var barterItems = await _context.BarterItem
                .Where(bi => bi.AppUserId != user.Id && bi.IsAvailable == true)
                .Include(bi => bi.AppUser)
                .Include(bi => bi.BarterType)
                .ToListAsync();

            return View(barterItems);
        }

        // GET: BarterItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            var barterItem = await _context.BarterItem
                .Include(b => b.AppUser)
                .Include(b => b.BarterType)
                .FirstOrDefaultAsync(m => m.BarterItemId == id);

            return View(barterItem);
        }

        public async Task<ActionResult> Create()
        {
            var BarterTypeOptions = await _context.BarterType
              .Select(bt => new SelectListItem() { Text = bt.Title, Value = bt.BarterTypeId.ToString() })
              .ToListAsync();

            var viewModel = new BarterItemFormViewModel();

            viewModel.BarterTypeOptions = BarterTypeOptions;


            return View(viewModel);
        }

        // POST: Products/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("BarterItemId,Title,Description,BarterTypeId,AppUserId,ImagePath,ImageFile,Value,Quantity,IsAvailable")]BarterItemFormViewModel viewModelItem)
        {
            try
            {
                var user = await GetCurrentUserAsync();

                var barterItem = new BarterItem
                {

                    Title = viewModelItem.Title,
                    Description = viewModelItem.Description,
                    BarterTypeId = viewModelItem.BarterTypeId, 
                    IsAvailable = viewModelItem.IsAvailable,
                    Value = viewModelItem.Value,
                    Quantity = viewModelItem.Quantity,
                    AppUserId = user.Id,

                };

                if (viewModelItem.Quantity == 0)
                {
                    viewModelItem.IsAvailable = false;
                }
                
                if (viewModelItem.ImageFile != null && viewModelItem.ImageFile.Length > 0)
                {
                
                    var fileName = Guid.NewGuid().ToString() + Path.GetFileName(viewModelItem.ImageFile.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", fileName);

                    barterItem.ImagePath = fileName;

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await viewModelItem.ImageFile.CopyToAsync(stream);
                    }

                }else
                {
                
                    /// a default img 
                }

                _context.BarterItem.Add(barterItem);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: BarterItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var viewModelItem = new BarterItemFormViewModel();
            var barterItem = await _context.BarterItem.Include(b => b.BarterType).FirstOrDefaultAsync(b => b.BarterItemId == id);
            var barterTypeOptions = await _context.BarterType
                .Select(bt => new SelectListItem()
                {
                    Text = bt.Title,
                    Value = bt.BarterTypeId.ToString()
                }).ToListAsync();

            viewModelItem.Title = barterItem.Title;
            viewModelItem.Description = barterItem.Description;
            viewModelItem.IsAvailable = barterItem.IsAvailable;
            viewModelItem.Value = barterItem.Value;
            viewModelItem.Quantity = barterItem.Quantity;
            viewModelItem.AppUserId = barterItem.AppUserId;
            viewModelItem.ImagePath = barterItem.ImagePath;
            viewModelItem.BarterTypeOptions = barterTypeOptions.ToList();

            return View(viewModelItem);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, BarterItemFormViewModel viewModelItem)
        {
            try
            {
                var itemEdit = await _context.BarterItem.Include(b => b.BarterType).FirstOrDefaultAsync(b => b.BarterItemId == id);

                itemEdit.Title = viewModelItem.Title;
                itemEdit.Description = viewModelItem.Description;
                itemEdit.BarterTypeId = viewModelItem.BarterTypeId;
                itemEdit.IsAvailable = viewModelItem.IsAvailable;
                itemEdit.Value = viewModelItem.Value;
                itemEdit.Quantity = viewModelItem.Quantity;
              
                    if (viewModelItem.ImageFile != null && viewModelItem.ImageFile.Length > 0)
                    {

                        var fileName = Guid.NewGuid().ToString() + Path.GetFileName(viewModelItem.ImageFile.FileName);
                        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", fileName);

                        itemEdit.ImagePath = fileName;

                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await viewModelItem.ImageFile.CopyToAsync(stream);
                        }
                            
                    }

                if (viewModelItem.Quantity == 0)
                {
                    itemEdit.IsAvailable = false;
                }

                _context.BarterItem.Update(itemEdit);
                await _context.SaveChangesAsync();


                return RedirectToAction("Details", new { id = id});
            }
            catch
            {
                return View();
            }
        }

        // GET: BarterItems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var barterItem = await _context.BarterItem
                .Include(b => b.AppUser)
                .Include(b => b.BarterType)
                .FirstOrDefaultAsync(m => m.BarterItemId == id);

            if (barterItem == null)
            {
                return NotFound();
            }

            return View(barterItem);
        }

        // POST: BarterItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var barterItem = await _context.BarterItem.FindAsync(id);
            _context.BarterItem.Remove(barterItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BarterItemExists(int id)
        {
            return _context.BarterItem.Any(e => e.BarterItemId == id);
        }
    }
}

SwapShop/Controllers/UsersController.cs
using SwapShop.Data;
using SwapShop.Models;
using SwapShop.Models.ViewModels.Profile;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace SwapShop.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {

        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        public UsersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {

            _context = context;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var user = await GetCurrentUserAsync();
            var users = await _context.ApplicationUsers
                .Where(bi => bi.Id != user.Id)
                .ToListAsync();

            return View(users);
        }

        // GET: Profile/Details/5
        public async Task<IActionResult> Details(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            var currentUser = await GetCurrentUserAsync();

            var userInfo = await _context.ApplicationUsers
                .Where(app => app.Id == user.Id)
                    .Include(bi => bi.MyBarterItems)
                    .Include(bi => bi.ReceivedTrades)
                        .ThenInclude(t => t.Sender)
                    .Include(bi => bi.SentTrades)
                        .ThenInclude(t => t.Receiver)
                    .ToListAsync();

            var userId = await _context.ApplicationUsers.FirstOrDefaultAsync(app => app.Id == id);

            var completedRequests = user.ReceivedTrades.Concat(user.SentTrades);

            var viewModel = new UserProfileViewModel()
            {
                User = user,
                AppUserId = userId.Id,
                BarterItems = userId.MyBarterItems.ToList(),
                ReceivedTrades = userId.ReceivedTrades.Where(t => t.IsCompleted == false).ToList(),
                SentTrades = userId.SentTrades.Where(t => t.IsCompleted == false).ToList(),
                CompletedTrades = completedRequests.Where(t => t.IsCompleted == true).ToList()
            };

            return View(viewModel);
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public async Task<ActionResult> Edit(int id)
        {
            var user = await GetCurrentUserAsync();
            var viewModel = new ProfileFormViewModel
            {
                AppUserId = user.Id,
                TagName = user.TagName,
                Location = user.Location,
                ImagePath = user.ImagePath
            };

            return View(viewModel);
        }

        // POST: Profiles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind("AppUserId,TagName,Location,ImagePath,ImageFile")]ProfileFormViewModel viewModelItem, int id)
        {
            try
            {
                var profileData = await GetCurrentUserAsync();

                profileData.TagName = viewModelItem.TagName;
                profileData.Location = viewModelItem.Location;


                if (viewModelItem.ImageFile != null && viewModelItem.ImageFile.Length > 0)
                {

                    var fileName = Guid.NewGuid().ToString() + Path.GetFileName(viewModelItem.ImageFile.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", fileName);

                    profileData.ImagePath = fileName;

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await viewModelItem.ImageFile.CopyToAsync(stream);
                    }

                }

                _context.ApplicationUsers.Update(profileData);
                await _context.SaveChangesAsync();

                return RedirectToAction("Details", new { id = viewModelItem.AppUserId });
            }

            catch
            {
                return View();
            }
        }
    }
}

SwapShop/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager;
@inject UserManager<ApplicationUser> userManager;


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SwapShop</title>
    <link rel="stylesheet" href="~/bootstrap.min (1).css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container">


                    <img src="~/images/SWAPShopLogoWhite.png" style="width: 20em; height: auto;">

                


                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Community</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BarterItems" asp-action="Index">Barter Items</a>
                        </li>


                        @if (signInManager.IsSignedIn(User))
                        {
                            // Get the current logged in user
                            Task<ApplicationUser> GetCurrentUserAsync() => userManager.GetUserAsync(User);

                            var user = await GetCurrentUserAsync();

                            var AppUserId = user.Id;

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Details" asp-route-id="@AppUserId">My Profile</a>
                            </li>
                        }

                        <form class="nav-item">
                            <input class="form-control mr-sm-2 text-light" type="text" placeholder="Search" name="searchBar" />
                            <button class="btn btn-primary my-2 my-sm-0" type="submit" asp-controller="Home" asp-action="Search">Search</button>
                        </form>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SwapShop 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>